apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: specmcp-ai
  namespace: specmcp-ai
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`specmcp.ai`) || Host(`www.specmcp.ai`)
      kind: Rule
      services:
        - name: specmcp-ai
          port: 80
  tls: {}
