variable "location" {
  description = "Azure region"
  type        = string
}

variable "resource_group_name" {
  description = "Name of the resource group"
  type        = string
}

variable "vnet_name" {
  description = "Name of the existing virtual network (for subnet creation)"
  type        = string
}

variable "vnet_id" {
  description = "ID of the existing virtual network (for private DNS zone VNet link)"
  type        = string
}

variable "server_name" {
  description = "Name of the PostgreSQL Flexible Server"
  type        = string
  default     = "psql-kevinryan-io"
}

variable "admin_username" {
  description = "Administrator login name for the PostgreSQL server"
  type        = string
  default     = "pgadmin"
}

variable "admin_password" {
  description = "Administrator password for the PostgreSQL server (generated by root module)"
  type        = string
  sensitive   = true
}

variable "databases" {
  description = "List of database names to create on the server"
  type        = list(string)
  default     = ["umami_db", "grafana_db"]
}
