apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: ">=0.70.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: observability
      interval: 1h
  install:
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    fullnameOverride: vm

    victoria-metrics-operator:
      enabled: true
      operator:
        disable_prometheus_converter: false
      nodeSelector:
        role: observability
      tolerations:
        - key: observability
          operator: Equal
          value: "true"
          effect: NoSchedule

    vmsingle:
      enabled: true
      spec:
        retentionPeriod: "31d"
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
        nodeSelector:
          role: observability
        tolerations:
          - key: observability
            operator: Equal
            value: "true"
            effect: NoSchedule

    vmagent:
      enabled: true
      spec:
        scrapeInterval: 30s
        selectAllByDefault: true
        nodeSelector:
          role: observability
        tolerations:
          - key: observability
            operator: Equal
            value: "true"
            effect: NoSchedule

    prometheus-node-exporter:
      enabled: true
      tolerations:
        - key: observability
          operator: Equal
          value: "true"
          effect: NoSchedule

    kube-state-metrics:
      enabled: true

    grafana:
      enabled: false

    defaultDashboards:
      enabled: true

    external:
      grafana:
        datasource: VictoriaMetrics

    defaultRules:
      create: true

    alertmanager:
      enabled: false
    vmalert:
      enabled: false
    vmauth:
      enabled: false
    vmcluster:
      enabled: false

    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false

    kubelet:
      enabled: true
